# Generated by Django 4.0.5 on 2022-06-21 14:07

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer'), ('None', 'None')], default='None', max_length=255)),
                ('contact_number', models.CharField(max_length=11, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=account.models.get_profile_pictures_directory)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.department')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_number', models.CharField(max_length=11, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=account.models.get_profile_pictures_directory)),
                ('facutly', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('room_number', models.IntegerField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.course')),
                ('examiners', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.teacher')),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateField()),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dashboard.faculty')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='account.teacher')),
            ],
        ),
    ]
