# Generated by Django 4.0.5 on 2022-06-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('account', '0003_alter_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='facutly',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.faculty'),
            preserve_default=False,
        ),
    ]
