# Generated by Django 4.0.5 on 2022-06-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_facutly_staff_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='facutly',
            new_name='faculty',
        ),
    ]
