# Generated by Django 4.0.5 on 2022-06-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_staff_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='contact_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
