# Generated by Django 4.0.5 on 2022-07-24 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_routine_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='examiners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='examiner', to='account.teacher'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='supervisor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervisor', to='account.teacher'),
        ),
    ]
