# Generated by Django 4.0.5 on 2022-07-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_course_department'),
        ('account', '0013_teacher_is_available'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Routine',
            new_name='Exam',
        ),
    ]
