# Generated by Django 4.0.5 on 2022-07-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='total_creadits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
