# Generated by Django 4.0.5 on 2022-07-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_teacher_total_creadits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='total_creadits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
