# Generated by Django 4.0.5 on 2022-08-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_exam_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='exams',
        ),
        migrations.AddField(
            model_name='routine',
            name='name',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
