# Generated by Django 4.0.5 on 2022-08-13 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_routine_exams_routine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='routine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.routine'),
        ),
    ]
