# Generated by Django 4.0.5 on 2022-09-14 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
