# Generated by Django 4.0.5 on 2022-09-14 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_room_shift'),
        ('account', '0023_routine_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department'),
            preserve_default=False,
        ),
    ]
