# Generated by Django 4.0.5 on 2022-09-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_routine_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
