# Generated by Django 4.0.5 on 2022-06-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='facutly',
            new_name='faculty',
        ),
    ]
